### PR TITLE
Update blocks.xml

### PR DESCRIPTION
**Pull request by wkwan**
Need to change "mods" to "Mods" or else you get an exception when the server starts when running on Ubuntu.

### CODE REVIEW

**Comment by mczero80** [comment]
I can confirm it on debian, I think the change is essential

**Comment by Markezzz** [comment]
I can also confirm this fix for ubuntu.

**Comment by IxeYgrek** [comment]
Hello,

Je confirme que ça fonctionne beaucoup mieux en faisant ça :)
(serveur chez NitroServ)
---
I can also confirm this fix for Nitroserv server

**Comment by wkwan** [comment]
Looks like it's been fixed!

**Comment by mczero80** [comment]
But there was no commit since february

**Comment by wkwan** [comment]
Was probably fixed a long time ago. I see the correct code in blocks.xml. Are you running into issues?

`	<block id="984" name="workingTv">
		<property name="Class" value="TV, Mods" />`

**Comment by mczero80** [comment]
No, but was sure that I fixed the typo manually a month ago. Probably wrong memory

**Pull request closed without merging**
